
CREATE DATABASE IF NOT EXISTS cafeteria;
USE cafeteria;


CREATE TABLE IF NOT EXISTS pedido (
    id INT(10) NOT NULL AUTO_INCREMENT,
    numero_pedido INT(10) NOT NULL,
    nome_cafe VARCHAR(50) NOT NULL DEFAULT '',
    valor_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS produtos (
    id INT(10) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NULL DEFAULT NULL,
    preco_unitario DECIMAL(20,6) NULL DEFAULT NULL,
    categoria VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS funcionarios (
    id INT(10) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL DEFAULT,
    cargo VARCHAR(50) NOT NULL DEFAULT,
    turno VARCHAR(50) NOT NULL DEFAULT,
    PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS avaliacao (
    id INT(10) NOT NULL AUTO_INCREMENT,
    pedido_id INT(10) NOT NULL,
    nota INT(1) NOT NULL,
    comentario TEXT NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_avaliacao_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) 
)